name: 删除workflow，清理工作流
on:
  #定时触发开始编译(把下面两个#去掉开启,时间设置请看定时编译说明)
  schedule:
    - cron: 0 0 1 * *

  workflow_dispatch:

jobs:
  del_workflow:
    runs-on: Ubuntu-24.04
    name: delete-workflow-runs
    steps:
    
      - name: 删除workflow，清理工作流
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
